### ISSUE TITLE
[bug] IssueService.Search() with a not empty JQL triggers 400 bad request

### ISSUE THREAD

**Issue by timwata** [andygrunwald/go-jira#291] opened 2020-05-03 07:26 UTC
## Describe the bug

When using the method `IssueService.Search()` with a not empty JQL, it triggers 400 bad request even if the JQL is correct.

## To Reproduce

Use `IssueService.Search()` with a not empty JQL.

## Expected behavior

No trigger 400 bad request if JQL is correct.

## Possible Solution

The root cause is the JQL gets escaped twice.
First one is `uv.Add("jql", url.QueryEscape(jql))` and second one is `u.RawQuery = uv.Encode()`.
A possible solution is just removing `url.QueryEscape()` from `uv.Add("jql",...)`.

https://github.com/andygrunwald/go-jira/blob/4b91cf2b135355de7ecee41727c3e65f4e7067bc/issue.go#L960-L987

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* go-jira version (git tag or she): 4b91cf2
* Go version (`go version`): 1.14.2
* Jira type (cloud or on-premise):cloud
* Operating System and version: macOS 10.15.3

**Comment by andygrunwald** [comment] 2020-05-03 07:28
Thanks @timwata.
Yesterday, we merged https://github.com/andygrunwald/go-jira/pull/268.
Maybe this is the cause.

//cc @kfoxb

**Comment by andygrunwald** [comment] 2020-05-03 07:53
I am working on a fix already. Gimme some time.

**Comment by andygrunwald** [comment] 2020-05-03 08:06
Fixed in #292 

Thanks @timwata

**Closed by andygrunwald** 2020-05-03 08:06 UTC
Labels: bug
