### ISSUE TITLE
Can't get comments

### ISSUE THREAD

**Issue by lexfrei** [andygrunwald/go-jira#245] opened 2019-12-04 16:55 UTC
Hi!

Can't get comments with your lib. My PoC code, mostly form your examples and #237:

<details>

```
package main

import (
	"fmt"
	"log"
	"strings"

	jira "github.com/andygrunwald/go-jira"
)

func main() {
	tp := jira.BasicAuthTransport{
		Username: strings.TrimSpace("XXXXX"),
		Password: strings.TrimSpace("XXXXX"),
	}

	client, err := jira.NewClient(tp.Client(), strings.TrimSpace("https://jira.XXXXX"))
	if err != nil {
		fmt.Printf("\nerror: %v\n", err)
		return
	}

	var issues []jira.Issue

	appendFunc := func(i jira.Issue) (err error) {
		issues = append(issues, i)
		return err
	}

	err = client.Issue.SearchPages("XXXXX", nil, appendFunc)
	if err != nil {
		log.Fatal(err)
	}

	for _, i := range issues {
		if i.Fields.Comments != nil {
			fmt.Printf("%d\n", len(i.Fields.Comments.Comments))

			for _, comment := range i.Fields.Comments.Comments {
				fmt.Println(comment.Body)
			}
		} else {
			fmt.Println("Comments is nil")
		}
	}
}
```

</details>

So, the output is `Comments is nil` for all issues.
But I can use `issues.Self` and get raw output via the link. All comments are present as expected.
Is this expected?
Lib version: master
Jira version: v8.4.2#804003-sha1:d21414f

**Comment by ghostsquad** [comment] 2019-12-07 23:41
I think this is a duplicate of #237

Specifically, this comment should help:
https://github.com/andygrunwald/go-jira/issues/237#issuecomment-550065420

**Closed by ghostsquad** 2019-12-07 23:41 UTC
Labels: duplicate
